# fly.toml app configuration file generated for apimotor on 2023-10-19T12:04:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apimotor"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
